//
//  FirstViewController.swift
//  HaritalarUygulamasi
//
//  Created by Beyza Gürbüz on 28.10.2024.
//

import UIKit

class FirstViewController: UIViewController,UITableViewDelegate,UITableViewDataSource{
    
    @IBOutlet weak var FirstTableView: UITableView!
    
    var careArray = [FaceCare] ()
    var selectedCare : FaceCare?

    override func viewDidLoad() {
        super.viewDidLoad()
        FirstTableView.delegate = self
        FirstTableView.dataSource = self
        
        let yagliSacDerisi = FaceCare(isim: "Yağlı Saç Derisi", bolge: "Dikkat!:Şakaklar,Boyun ve Kulak arkası",aciklama:" Yağlı saç derisi için etkili bir bakım rutini oluşturmak, sebum üretimini dengelemek ve saç sağlığını korumak için önemlidir. İlk adım olarak, yağlı saç derisine özel şampuanlar kullanarak saçınızı yıkayın. Bu şampuanlar, fazla yağı temizlemeye yardımcı olur ve genellikle jel veya köpük formundadır. Saçınızı yıkarken ılık su tercih edin ve şampuanı saç derisine masaj yaparak uygulayın; bu, kan dolaşımını artırır. Yıkama sıklığını 2-3 günde bir yapmaya özen gösterin, gerekirse daha sık yıkayabilirsiniz.Haftada bir, saç derisi için peeling yaparak ölü deri hücrelerini ve yağ kalıntılarını temizleyin. Bu işlem için doğal peeling tarifleri kullanabilir ya da piyasada bulunan saç derisi peeling ürünlerinden faydalanabilirsiniz. Peeling işleminden sonra, saç uçlarına yağsız saç kremi uygulayarak nem dengesini sağlayabilirsiniz; ancak kremi asla saç derisine temas ettirmemeye dikkat edin.Ayrıca, saç bakımında ağırlık yapmayan ürünler kullanmak önemlidir. Saç spreyleri ve şekillendiricilerin hafif ve yağsız olmasına özen gösterin. Eğer doğal ürünleri tercih ediyorsanız, çay ağacı yağı ve aloe vera gibi içerikler, saç derisini yatıştırmaya ve dengelemeye yardımcı olabilir. Çay ağacı yağını şampuanınıza ekleyebilir veya aloe vera jelini doğrudan saç derinize uygulayabilirsiniz.Beslenme de yağlı saç derisinin sağlığı için kritik bir faktördür. Dengeli bir diyet oluşturun; bol sebze, meyve ve tam tahıllar tüketin, aşırı yağlı ve şekerli gıdalardan kaçının. Yeterli su tüketimi de cildin ve saç derisinin nem dengesini korumak için gereklidir.Son olarak, stresten kaçınmak da önemlidir. Rahatlama yöntemleri olarak yoga veya meditasyon gibi aktiviteleri hayatınıza dahil edin. Eğer bu önerilere rağmen yağlı saç derisi sorunları devam ederse, bir dermatologdan yardım alarak profesyonel öneriler ve tedavi yöntemleri hakkında bilgi alabilirsiniz. Bu düzenli ve dikkatli bakım rutini ile yağlı saç derinizi sağlıklı bir şekilde yönetebilirsiniz. ", gorsel: UIImage(named: "sacDerisi")!)
        let kuruSacDerisi = FaceCare(isim: "Kuru Saç Derisi:", bolge: "Dikkat!: Saç Çizgileri-Verteks Bölgesi",aciklama:" Kuru saç derisi bakımı, saçın doğal nem dengesini koruyarak kaşıntı, pul pul dökülme gibi rahatsızlıkları önlemeye yönelik aşamalardan oluşur. İlk adım olarak, nemlendirici özellikli şampuanlar tercih edin. Özellikle kuru saç derisine özel olarak formüle edilmiş, sülfatsız ve nazik temizleyiciler içeren şampuanlar, saç derisinin doğal yağlarını korumaya yardımcı olur. Saçınızı yıkarken ılık su kullanarak saç derisinin daha fazla kurumasını engelleyebilirsiniz. Saç yıkama sonrası, yoğun nemlendirici bir saç kremi kullanmak kuru saç derisini rahatlatır ve saç tellerinin daha sağlıklı görünmesini sağlar. Saç kremini, özellikle saç uçlarına yoğunlaşarak uygulayın ve saç derisiyle temasından kaçının. Haftada bir kez, daha yoğun bir bakım için nemlendirici saç maskesi kullanabilirsiniz; bu, saç derisinin daha derinlemesine nemlenmesine katkı sağlar. Doğal yağlar, kuru saç derisi için oldukça faydalıdır. Hindistancevizi yağı, jojoba yağı veya argan yağı gibi yağları doğrudan saç derinize uygulayarak masaj yapın. Bu yağlar, saç derisine yoğun nem verir ve tahriş olmuş bölgeleri yatıştırır. Bu uygulamayı haftada bir veya iki kez yapabilirsiniz; yağı saç derisine sürdükten sonra 15-20 dakika bekleyip yıkayın. Ayrıca, saç derisi peelingi kuru cilt hücrelerinden kurtulmanıza ve nemlendirici ürünlerin daha etkili olmasına yardımcı olur. Kuru saç derisine özel peeling ürünleri veya doğal exfoliant seçenekleri tercih edebilirsiniz. Saç derisi peelingini ayda bir veya iki kez uygulamak yeterli olacaktır.Beslenme de saç sağlığı üzerinde büyük rol oynar. Omega-3 yağ asitleri açısından zengin bir diyet uygulayarak saç derisinin nemlenmesini destekleyebilirsiniz. Balık, ceviz, keten tohumu gibi besinler tüketerek saç derinizin daha sağlıklı kalmasını sağlayabilirsiniz. Bol su içmek de cilt ve saç sağlığı için oldukça önemlidir; bu yüzden yeterli miktarda su tüketmeye özen gösterin. Son olarak, kuru saç derisine sahip kişilerin ısı ile şekillendirme araçlarını en aza indirmesi önerilir. Fön makinesi veya saç düzleştiricileri kullanırken düşük ısı ayarında çalıştırmaya özen gösterin, çünkü aşırı sıcaklık saç derisini daha da kurutabilir. Bu düzenli bakım rutini ile kuru saç derinizi daha sağlıklı ve dengeli tutabilirsiniz. ", gorsel: UIImage(named: "kuruSac")!)
        let normalSacDerisi = FaceCare(isim: "Normal Saç Derisi", bolge: "Dikkat!: genel kotrol yapılmalı.",aciklama:" Normal saç derisini sağlıklı tutmak için dengeli bir bakım rutini izlemek, saçın doğal yapısını ve nem dengesini korumaya yardımcı olur. İlk adım olarak, nazik ve dengeli formüle sahip bir şampuan kullanarak saçınızı temizleyin. Normal saç derisi, sık yıkama gerektirmediği için 2-3 günde bir şampuanlamak yeterlidir. Bu tür şampuanlar saç derisinin doğal yağlarını korur ve saç tellerine zarar vermez. Yıkama sonrası, saç tellerini beslemek için hafif bir saç kremi kullanabilirsiniz. Saç kremini saç uçlarına uygulayın ve saç derisinden uzak tutun; bu, saçın nemli kalmasına ve kırılganlığını azaltmaya yardımcı olur. Haftada bir veya iki kez, saç maskesi veya krem ile yapılan bakım uygulamaları, saç tellerinin parlak ve güçlü kalmasına destek sağlar. Ayrıca, doğal yağlarla saç derisine masaj yapmak normal saç derisini daha da besler. Argan yağı veya jojoba yağı gibi hafif yağları tercih edin. Yağı saç derinize nazikçe masaj yaparak uygulayın, bu dolaşımı artırır ve saçın doğal parlaklığını korur. Yağ uygulamasını haftada bir yapabilirsiniz ve saçınızı 15-20 dakika sonra durulayabilirsiniz.Normal saç derisi genellikle ekstra peeling veya yoğun bakım gerektirmese de, ayda bir kez saç derisi peelingi yapmak, ölü deri hücrelerini temizler ve saç derisinin nefes almasını sağlar. Doğal peeling ürünleri veya nazik bir saç fırçası ile yapılan bu işlem, saç köklerinin daha sağlıklı kalmasına yardımcı olur.Son olarak, saç sağlığını korumak için dengeli beslenme ve yeterli su tüketimi önemlidir. Vitamin ve mineral yönünden zengin yiyecekler tüketmek, saç derisinin canlı ve sağlıklı kalmasını sağlar. Özellikle yeşil yapraklı sebzeler, fındık, ceviz ve su içeriği yüksek meyveler, saç ve saç derisi sağlığı için faydalıdır. ", gorsel: UIImage(named: "normalSac")!)
        let duyarlıSacDerisi = FaceCare(isim: "Duyarlı Saç Derisi", bolge: "Dikkat!: genel kotrol yapılmalı. ",aciklama:"Duyarlı saç derisi bakımı, tahrişi önlemek ve saç derisini rahatlatmak için nazik ve dikkatli bir yaklaşıma ihtiyaç duyar. İlk adım olarak, hassas saç derisine özel formüle edilmiş şampuan kullanarak saçınızı yıkayın. Sülfatsız ve parfümsüz şampuanlar, tahrişi en aza indirgeyerek nazik bir temizlik sağlar. Saçınızı yıkarken suyun sıcaklığına dikkat edin; ılık su kullanmak, saç derisini koruyarak kurumasını ve tahriş olmasını önler. Yıkama sonrasında saç tellerini beslemek için hafif ve hassas saç kremleri tercih edin. Saç kremini yalnızca saç uçlarına uygulayın; saç derisinden uzak tutarak, herhangi bir hassasiyeti önleyebilirsiniz. Ayrıca, krem kullanırken ürünlerin paraben ve parfüm içermemesine dikkat etmek önemlidir. Saç uçlarına uyguladığınız saç kremi, saçların daha kolay taranmasını ve kopmasını önler.Duyarlı saç derisine sahip kişiler için doğal ve yatıştırıcı yağlarla bakım yapmak oldukça faydalıdır. Özellikle, saç derisine zarar vermeyen jojoba yağı veya aloe vera jeli gibi doğal ürünler, saç derisini yatıştırarak nem dengesini korur. Yağı saç derinize nazik masaj hareketleriyle uygulayın, böylece kan dolaşımını artırarak saç derisinin rahatlamasına yardımcı olabilirsiniz. Uygulamayı haftada bir yaparak etkili bir bakım sağlayabilirsiniz. Duyarlı saç derisinde ekstra dikkat edilmesi gereken bir diğer adım ise peeling işleminden kaçınmak veya çok nazik bir peeling yapmak. Peeling yaparken yalnızca hassas ciltler için uygun olan ürünleri tercih edin veya haftada bir, nazik hareketlerle masaj yaparak uygulayın. Saç derisinin tahriş olmaması için bu işlemi olabildiğince hafif tutun.Saç sağlığını desteklemek için dengeli beslenme duyarlı saç derisi bakımında da önemlidir. Bol sebze, meyve, tam tahıl ve su tüketimi, saç derisini içten destekler ve direncini artırır. Özellikle cilt sağlığı için gerekli olan çinko, omega-3 yağ asitleri ve E vitamini içeren yiyecekler, saç derisinin hassasiyetini azaltabilir.Son olarak, saç şekillendirici ısı araçlarından mümkün olduğunca kaçınmak veya düşük ısıda kullanmak önemlidir. Duyarlı saç derisi sıcaklıktan etkilenebilir ve bu da tahrişe yol açabilir. Bu bakım adımlarını takip ederek, duyarlı saç derinizi sağlıklı ve rahat bir şekilde koruyabilirsiniz.", gorsel: UIImage(named: "duyarliSac")!)
        let karmaSacDerisi = FaceCare(isim: "Karma Saç Derisi", bolge: "Dikkat!: genel kotrol yapılmalı.",aciklama:"Karma saç derisi bakımı, saç derisindeki yağlı ve kuru bölgeleri dengelemeye yönelik ürünlerin ve adımların özenle seçilmesini gerektirir. İlk olarak, karma saç derisine uygun, sülfatsız bir şampuan tercih edin. Bu tip şampuanlar, saçın doğal yağ dengesini korurken, saç derisindeki fazla yağı nazikçe temizler ve kuru bölgeleri nemlendirir. Saçınızı ılık suyla yıkayarak, doğal nemin korunmasına yardımcı olabilir ve kuruluğun önüne geçebilirsiniz. Şampuanlama sonrasında, hafif ve nemlendirici bir saç kremi kullanarak özellikle saç uçlarını besleyin. Saç kremini yalnızca uçlara uygulayın ve saç derisinden uzak tutmaya özen gösterin. Bu şekilde, kuru bölgelere nem sağlarken saç derisinin yağ dengesini korumuş olursunuz. Haftada bir ya da iki kez, bu rutini daha yoğun bir nemlendirici maske ile destekleyerek, saç uçlarının yumuşak kalmasına katkıda bulunabilirsiniz. Haftada bir kez, saç derisine uygun besleyici bir yağ veya saç maskesi ile saç derisini ve kuru bölgeleri destekleyin. Hindistancevizi yağı, jojoba yağı veya argan yağı gibi hafif nemlendiriciler, özellikle kuru bölgeleri beslerken, fazla yağı artırmadan saç derisinin sağlıklı kalmasına yardımcı olur. Yağı, sadece ihtiyaç duyulan bölgelere uygulamak, karma saç derisi için ideal bir denge sağlar. Ayda bir defa, nazik bir saç derisi peelingi ile ölü derileri temizlemek ve yağlı bölgelerin tıkanmasını önlemek faydalı olacaktır. Ancak, karma saç derisine sahip olduğunuz için, peelingi sadece yağlı bölgelere hafifçe uygulayın ve kuru bölgeleri koruyarak aşırı tahrişten kaçının. Bu, saç derinizin daha sağlıklı ve dengeli kalmasını sağlar.Son olarak, dengeli beslenme ve yeterli su tüketimi karma saç derisini içten destekler. Özellikle Omega-3, çinko, E vitamini gibi besin öğelerini içeren gıdalar tüketmek, saç derisinin yağ ve nem dengesini destekler. Saç sağlığı için ayrıca şekillendirme araçlarının minimum düzeyde, düşük ısıda kullanılmasına dikkat edin. Bu aşamaları takip ederek karma saç derinizi rahatlatabilir ve dengeleyebilirsiniz.  ", gorsel: UIImage(named: "karmaSac")!)
        let kuruCilt = FaceCare(isim: "Kuru Cilt", bolge: "Dikkat!Diz-Dirsek bölgeleri ",aciklama:"Kuru cilde sahip kol ve bacaklar için nemlendirme odaklı, özenli bir bakım rutini oluşturmak, cildin esnek ve yumuşak kalmasına yardımcı olur. İlk adım olarak, nemlendirici özellikli bir duş jeli veya sabun tercih edin. Sıcak su yerine ılık su kullanarak yıkanmak, ciltteki doğal yağları koruyarak kuruluğun azalmasına yardımcı olur. Özellikle shea yağı, badem yağı veya zeytinyağı içeren temizleyiciler cildin yumuşaklığını destekler.Duş sonrası, henüz nemliyken cilde yoğun nemlendirici bir vücut losyonu veya krem uygulayın. Kol ve bacaklardaki kuru bölgeleri özellikle hedefleyerek, cildin nemi hapsetmesini sağlayabilirsiniz. Hyaluronik asit, gliserin, shea yağı gibi içeriklere sahip nemlendiriciler, cildin su tutma kapasitesini artırır ve uzun süreli nem sağlar. Bu adımı her duş sonrası uygulayarak cildinizin daha sağlıklı kalmasını sağlayabilirsiniz.Cildinizin ekstra bakıma ihtiyaç duyduğu dönemlerde, haftada bir kez nemlendirici bir vücut yağı veya kuru ciltler için özel maske kullanabilirsiniz. Vücut yağlarını veya maskeleri duş sonrası, hafif nemli cilde uygulayarak daha iyi emilim sağlayabilirsiniz. Argan yağı, jojoba yağı veya E vitamini içeren ürünler, kuru cildi besler ve daha pürüzsüz bir his bırakır. Düzenli peeling, ölü deriyi uzaklaştırarak nemlendirici ürünlerin daha iyi emilmesine katkı sağlar. Haftada bir kez nazik bir vücut peelingi uygulayın. Hindistancevizi yağı veya şeker bazlı peelingler, cildi tahriş etmeden pürüzsüzleştirir. Peeling işlemi sonrasında tekrar yoğun nemlendirici bir krem veya vücut yağı uygulamak, cildin yenilenmiş ve yumuşak kalmasına yardımcı olur. Son olarak, dengeli beslenme ve su tüketimi cilt sağlığı için önemlidir. Su içeriği yüksek meyve ve sebzeler tüketmek, içten nem sağlamaya yardımcı olur. Cildin kuruluğunu önlemek için her gün yeterli miktarda su içmek ve bol lifli besinler tüketmek, dış bakımla birleştiğinde kol ve bacaklardaki kuru cildi destekler ve nem dengesini korur. Bu aşamaları düzenli uygulayarak, kuru ciltli kol ve bacaklarınızda daha sağlıklı ve yumuşak bir görünüm elde edebilirsiniz. ", gorsel: UIImage(named: "nemlendirici")!)
        let yagliCilt = FaceCare(isim: "Yağlı Cilt", bolge: "Dikkat!: Üst kol-Üst bacak",aciklama:"Yağlı cilde sahip kol ve bacaklar için bakım rutini, fazla yağı dengelemeye ve ciltteki tıkanmaları önlemeye odaklanır. İlk adım olarak, yağ dengesini sağlayan bir duş jeli veya sabun kullanarak cildinizi temizleyin. Salisilik asit veya çay ağacı yağı gibi içerikler, cildin fazla yağını nazikçe temizlerken gözeneklerin tıkanmasını önler. Bu içerikler, ciltte yağ dengesini koruyarak pürüzsüz bir yüzey sağlar. Duştan sonra, yağlı ciltlere uygun, hafif formüllü bir nemlendirici veya losyon uygulayın. Yağsız ve su bazlı nemlendiriciler, cildi nemlendirirken gözeneklerin tıkanmasını engeller. Aloe vera veya hyaluronik asit içeren nemlendiriciler, cilde hafif bir nem sağlarken yağlanma yapmaz, bu da kol ve bacakların gün boyunca daha mat kalmasını destekler. Ciltteki yağ dengesini korumak için haftada bir kez, özellikle kol ve bacaklarda nazik bir peeling yaparak ölü hücreleri arındırın. Kil içeren peelingler veya salisilik asit içeren hafif eksfoliantlar, gözenekleri temizleyerek fazla yağı azaltır ve cildin daha temiz görünmesini sağlar. Peeling sonrası cilde hafif bir nemlendirici uygulamak, tahrişi önler ve sağlıklı bir parlaklık kazandırır. Ekstra bakım için ayda bir veya iki kez, cildi yağdan arındıran kil maskesi kullanabilirsiniz. Kol ve bacaklarınıza uygulayabileceğiniz bu maskeler, fazla yağı emer ve cilt yüzeyini mat hale getirir. Yeşil çay özü veya çinko içeren maskeler, cildin yağ dengesini düzenlerken yatıştırıcı özellik sağlar. Maskeyi uyguladıktan sonra ılık su ile durulayarak ardından hafif bir nemlendiriciyle bakımınızı tamamlayabilirsiniz.Son olarak, dengeli beslenme yağlı cilt bakımında önemli bir faktördür. Şekerli ve yağlı yiyeceklerden uzak durarak  ", gorsel: UIImage(named: "nemlendirici2")!)
        let normalCilt = FaceCare(isim: "Normal Cilt", bolge: "Dikkat!Diz-Dirsek bölgeleri ",aciklama:"Kol ve bacak bakımında etkili ve düzenli bir bakım rutini, doğru sırayla kullanılan içeriklerle cildin daha pürüzsüz ve sağlıklı görünmesini sağlar. İşte bakım adımları ve içerikleri ön planda tutan sıralama:Temizlik (Duşta veya Banyoda)İlk adımda ciltteki kirleri ve ölü derileri arındırmak için cildinize uygun bir duş jeli veya vücut sabunu kullanın. Cildi kurutmadan temizleyen ve nem dengesini koruyan ürünler idealdir. İçeriğinde sülfatsız temizleyiciler ve yulaf ekstresi olan ürünler, hassas ciltlerde bile iritasyona yol açmadan temizler.Eksfoliasyon (Haftada 1-2 Kez)Cilt yüzeyindeki ölü derilerden kurtulmak için eksfoliasyon adımını uygulayın. AHA’lar (laktik asit, glikolik asit) veya BHA (salisilik asit) içeren peeling ürünleri, cilt yüzeyini nazikçe arındırır ve yumuşaklık kazandırır. Kimyasal eksfoliyanlar tercih edilmiyorsa, jojobayağı içeren doğal partiküllü scrub’lar da kullanılabilir. Haftada bir veya iki kez eksfoliasyon yaparak cildin tazelenmesini sağlayabilirsiniz.Tıraş veya Epilasyon (Eksfoliasyon Sonrası)Eksfoliasyon sonrası tıraş veya epilasyon yapmak, cildin daha pürüzsüz olmasına yardımcı olur. Tıraş sonrası tahrişi azaltmak için aloe vera veya panthenol gibi yatıştırıcı içerikler içeren kremler kullanabilirsiniz.Nemlendirme (Duş Sonrası ve Günlük Kullanım) Duş sonrasında, cildiniz hâlâ hafif nemliyken vücut losyonu veya krem uygulayın. İçeriğinde gliserin, hyaluronik asit ve seramid bulunan ürünler ciltteki nemi hapsederek uzun süreli nemlendirme sağlar. Kol ve bacaklar için yoğun nemlendirici ürünler tercih ediyorsanız, sheayağı ve jojoba yağı gibi besleyici yağları içeren losyonları seçebilirsiniz.Koruma (Günlük Güneş Koruyucu Kullanımı) Açıkta kalan cilt bölgelerine özellikle yaz aylarında güneş koruyucu uygulayın. Çinko oksit veya titanyum dioksit gibi geniş spektrumlu mineral filtrelere sahip güneş koruyucular, UV ışınlarına karşı etkili bir bariyer sağlar. Koruma, cildin erken yaşlanmasını önlemeye de yardımcı olur.", gorsel: UIImage(named: "normal")!)
        let karmaCilt = FaceCare(isim: "Karma Cilt", bolge: "Dikkat!Diz-Dirsek bölgeleri ",aciklama:"Karma cilt, hem yağlı hem de kuru bölgeleri bir arada barındıran bir cilt tipidir. Bu cilt tipinin bakımı, her iki bölgenin ihtiyaçlarını dengelemeyi gerektirir. İşte kol ve bacak bakımını, ürün içeriklerini ve bakım sırasını dikkate alarak ayrıntılı olarak ele alan bir rehber:             1. Temizlik Ürün: pH dengeli bir temizleyici (örneğin, aloe vera ve çay ağacı yağı içeren bir jel temizleyici)Karma cilt bakımının ilk adımı, ciltteki kir ve fazla yağdan arınmaktır. pH dengeli bir temizleyici ile nazik bir şekilde cildinizi temizleyin. Aloe vera, cildin nem dengesini korurken, çay ağacı yağı ise yağlı bölgelere uygulandığında antiseptik etkisi ile sivilce oluşumunu önleyebilir.     2. Tonik Ürün: alkol içermeyen tonik (örneğin, gül suyu veya yeşil çay özü) Temizlikten sonra tonik kullanarak cildin pH dengesini yeniden sağlamalısınız. Alkol içermeyen tonikler, ciltteki yağlanmayı kontrol ederken, kuru bölgeleri de besleyerek cildin dengesini korur.                       3. Peeling Ürün: doğal içerikli peeling (örneğin, kahve telvesi veya şeker peelingi) Cildin ölü hücrelerden arınması için haftada bir veya iki kez peeling yapmanız önerilir. Doğal içerikli bir peeling, cildin yumuşak kalmasını sağlarken, kan dolaşımını artırarak cildin yenilenmesine yardımcı olur.                      4. Maske Ürün: nemlendirici maske (örneğin, hyaluronik asit ve jojoba yağı içeren maske) Maske uygulaması, cildin ihtiyaç duyduğu besinleri almasını sağlar. Hyaluronik asit, cildin nemini artırırken, jojoba yağı ise yağlı ve kuru bölgeleri dengeleyerek cildin elastikiyetini artırır.                  5. Nemlendirici Ürün: hafif dokulu nemlendirici (örneğin, aloe vera ve shea yağı içeren) Bakım rutininizi tamamlamak için hafif dokulu bir nemlendirici kullanmalısınız. Aloe vera, su bazlı bir formül ile cildin nem dengesini sağlarken, shea yağı ise kuru bölgeleri besler.       6. Güneş Koruyucu Ürün: SPF içeren güneş koruyucu (örneğin, mineral tabanlı) Son olarak, dışarı çıkmadan önce mutlaka güneş koruyucu kullanmalısınız. SPF içeren ürünler, cildin UV ışınlarından korunmasına yardımcı olur. Özellikle karma ciltlerde, mineral tabanlı ürünler tercih edilmelidir.  ", gorsel: UIImage(named: "karma")!)
        let duyarlıCilt = FaceCare(isim: "Duyarlı Cilt", bolge: "Dikkat!Diz-Dirsek bölgeleri ",aciklama:"Duyarlı cilt bakımı, özenli ve nazik bir yaklaşım gerektirir. İlk adım, nazik bir temizleyici kullanarak cildin kir ve yağdan arınmasını sağlamaktır; aloe vera ve yulaf ezmesi içeren pH dengeli bir temizleyici tercih edilmelidir. Temizleme sonrası alkol içermeyen, gül suyu veya papatya özlü tonik ile cildin pH dengesini yeniden sağlamak önemlidir. Haftada bir, laktik asit içeren yumuşak bir kimyasal peeling uygulayarak cildin ölü hücrelerden arınması sağlanabilir. Ardından, aloe vera ve hyaluronik asit içeren yatıştırıcı ve nemlendirici bir maske cildin rahatlamasına yardımcı olur. Nemlendirici olarak, hipoalerjenik ve parfümsüz shea yağı ve jojoba yağı içeren bir ürün kullanmak cildin nem dengesini korur. Son olarak, mineral tabanlı bir güneş koruyucu ile cilt UV ışınlarından korunmalı ve tahrişten uzak tutulmalıdır. Bu adımları düzenli olarak takip ederek, duyarlı cilt tipinin sağlıklı ve dengeli bir görünüm kazanması sağlanabilir.  ", gorsel: UIImage(named: "duyarli")!)
        let olgunCilt = FaceCare(isim: "Olgun Cilt", bolge: "Dikkat!Diz-Dirsek bölgeleri ",aciklama:"Olgun cilt bakımı, cildin yaşlanma belirtilerini azaltmak ve sağlıklı görünümünü korumak için özel bir yaklaşım gerektirir. İlk olarak, zeytinyağı ve süt proteinleri içeren besleyici bir temizleyici ile cilt nazikçe temizlenmelidir; bu, cildin nem dengesini korumaya yardımcı olur. Ardından, gül suyu ve hyaluronik asit içeren nemlendirici bir tonik kullanarak cildin pH dengesini sağlamalısınız. Haftada bir veya iki kez, papaya enzimleri veya laktik asit içeren yumuşak bir peeling ile ölü hücrelerden arınmak önemlidir. Sonrasında, avokado ve shea yağı içeren yoğun nemlendirici bir maske ile cildin derinlemesine beslenmesini sağlayabilirsiniz. Nemlendirici olarak, kolajen ve peptitler içeren zengin bir formül kullanarak cildin elastikiyetini artırmak ve nem dengesini korumak gerekir. Son olarak, dışarı çıkmadan önce mineral tabanlı ve yaşlanma karşıtı özelliklere sahip SPF içeren güneş koruyucu kullanmak, UV ışınlarından koruma sağlar. Bu adımları düzenli olarak takip ederek, olgun cilt tipinizin sağlıklı, genç ve canlı bir görünüm kazanmasını sağlayabilirsiniz.  ", gorsel: UIImage(named: "olgun")!)
        

        careArray = [yagliSacDerisi,kuruSacDerisi,normalSacDerisi,duyarlıSacDerisi,karmaSacDerisi,kuruCilt,yagliCilt,normalCilt,karmaCilt,duyarlıCilt,olgunCilt]
    }
    

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return careArray.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = UITableViewCell()
        cell.textLabel?.text = careArray[indexPath.row].isim
        return cell
    }
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        selectedCare = careArray[indexPath.row]
        performSegue(withIdentifier: "toFaceDetailsVC", sender: nil)
    }
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "toFaceDetailsVC" {
            let destinationVC = segue.destination as! FaceDetailsViewController
            destinationVC.secilenUrun = selectedCare
            
        }
    }


}
