//
//  ViewController.swift
//  HaritalarUygulamasi
//
//  Created by Beyza Gürbüz on 21.10.2024.
//

import UIKit
import MapKit

class ViewController: UIViewController,UITableViewDelegate,UITableViewDataSource  {
    @IBOutlet weak var tableView: UITableView!
    var careArray = [Care] ()
    var selectedCare : Care?
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        tableView.delegate = self
        tableView.dataSource = self
        
        //bakım ürünleri
        let normalCilt = Care(isim: "NORMAL CİLT", bolge: "Dikkat!: T bölgesi dikkatli izlenmelidir.",aciklama:"Gündüz Bakımı Gündüz cilt bakım rutini, cildin dış etkenlere karşı korunmasını sağlamak için kritik bir adımdır. Temizlik: Cildinizi nazik bir temizleyici ile arındırmalısınız. Seramidler, hyaluronik asit ve gliserin içeren temizleyiciler, cildin nem dengesini korurken derinlemesine temizlik sağlar.Tonik: Alkol içermeyen, cadı fındığı ve aloe vera gibi bileşenler içeren bir tonik kullanarak cildin pH dengesini sağlamalı ve gözenekleri sıkılaştırmalısınız.   Serum: Cilt tonunu eşitlemek ve aydınlatmak için niacinamide ve çinko içeren bir serum tercih edebilirsiniz. Ayrıca, C vitamini ve E vitamini kombinasyonu içeren serumlar, güçlü antioksidan koruma sağlar. Nemlendirici: Hafif bir nemlendirici, aloe vera ve hyaluronik asit içermelidir. Bu bileşenler, cildin derinlemesine nemlenmesini sağlar. Güneş Koruyucu: Geniş spektrumlu bir güneş koruyucu, Mexoryl gibi bileşenlerle UV ışınlarına karşı koruma sağlamalıdır. Ayrıca, gliserin içeriği ile cilde nem kazandırmalıdır.Gece Bakımı Gece cilt bakımı, cildin onarıldığı ve yenilendiği bir süreçtir. Temizlik: Cildi nazikçe temizlemek için jojoba yağı ve güneş yağı içeren temizleyiciler veya mikroskopik yağlar ile formüle edilmiş micellar sular kullanabilirsiniz. Tonik: Çay ağacı yağı ve balsam içeren tonikler, gözenekleri sıkılaştırırken ciltteki yağı dengeler. Serum: Retinoid içeren serumlar, cilt yenilenmesini desteklerken, hyaluronik asit ile nemlendirir.Nemlendirici: Seramidler ve niacinamide içeren nemlendiriciler, cildin onarımını desteklerken gece boyunca nem kaybını önler. Maske (haftada 1-2 kez): Gül suyu ve hyaluronik asit içeren maskeler, cildi nemlendirir. Ayrıca, avokado gibi besleyici bileşenler içeren maskeler, cildi derinlemesine besleyerek dolgunluk kazandırır. ", gorsel: UIImage(named: "careSprey")!)
        let kuruCilt = Care(isim: "KURU CİLT", bolge: "Yanaklar-Göz-Dudak çevresi",aciklama:" Kuru Cilt Bakım Aşamaları Kuru cilt bakımı, cildin nem dengesini korumak ve kuruluğun sebep olduğu rahatsızlıkları azaltmak için özel bir dikkat gerektirir. İlk adım olarak, cilt temizliği için nazik bir temizleyici tercih edilmelidir. Hyaluronik asit, seramidler ve glycerin gibi bileşenler içeren bir temizleyici, cildin nemini kaybetmeden arınmasını sağlar. Temizlikten sonra tonik aşamasına geçilmelidir. Kuru ciltler için alkol içermeyen tonikler tercih edilmelidir. Aloe vera ve bitkisel özler içeren tonikler, cildin nem dengesini sağlarken, yatıştırıcı etkileri sayesinde ciltteki tahrişi azaltır. Ardından, cildin nemlendirilmesi için zengin içerikli bir serum kullanılmalıdır. Hyaluronik asit, skualen ve vitamin E gibi nemlendirici bileşenler içeren serumlar, cildin derinlemesine beslenmesini ve nemlenmesini sağlar. Nemlendirme aşamasında, cildin kurumasını önlemek için yoğun bir nemlendirici kullanılması önerilir. Shea yağı, aloe vera ve jojoba yağı içeren nemlendiriciler, ciltte uzun süreli bir nem hissi bırakırken, cilt bariyerini güçlendirir.Gece bakımında, yoğun bir nemlendirici veya besleyici maske kullanarak cildin gece boyunca onarıma uğraması sağlanmalıdır. Avokado yağı, hyaluronik asit ve balsam içeren maskeler, cildin derinlemesine beslenmesine yardımcı olur. Haftada 1-2 kez kullanılacak bu maskeler, cildin kuruluğunu gidermekte etkili olur.Son olarak, cildin dış etkenlerden korunması için gündüzleri geniş spektrumlu bir güneş koruyucu kullanılması şarttır. Zinc oxide ve titanium dioxide gibi fiziksel güneş koruyucular, cildi UV ışınlarına karşı korurken, içeriklerindeki glycerin ile cildin nemli kalmasına yardımcı olur. Bu adımlarla kuru cilt bakım rutininiz, cildin sağlıklı, pürüzsüz ve nemli kalmasını sağlar.", gorsel: UIImage(named: "faceTonic")!)
        let yagliCilt = Care(isim: "YAĞLI CİLT", bolge: "Dikkat!: Sebum aktifliği T Bölgesi",aciklama:"Yağlı Cilt Bakım Aşamaları Yağlı ciltler için bakım rutini, aşırı yağ üretimini dengelemek ve gözenekleri temiz tutmak için özel bir dikkat gerektirir. Gündüz bakımında ilk adım, cilt temizliği olmalıdır. Salicylic acid veya BHA (Beta Hydroxy Acid) içeren bir temizleyici, cildin derinlemesine temizlenmesine ve gözeneklerin açılmasına yardımcı olurken, yağın ve kirin arınmasını sağlar. Çay ağacı yağı gibi doğal bileşenler içeren temizleyiciler, ciltteki iltihaplanmayı azaltarak akne oluşumunu engelleyebilir.Temizlik sonrası tonik kullanmak önemlidir. Alkol içermeyen, niacinamide ve cadı fındığı içeren tonikler, cildin pH dengesini sağlarken gözenekleri sıkılaştırmaya yardımcı olur. Ardından, serum aşamasına geçilmelidir. Niacinamide içeren serumlar, ciltteki yağ üretimini dengeleyerek gözeneklerin görünümünü azaltır. Ayrıca, hyaluronik asit ile formüle edilmiş serumlar, cildi nemlendirirken yağlı his bırakmadan derinlemesine besler.Nemlendirme aşamasında, hafif ve yağsız bir nemlendirici tercih edilmelidir. Glycerin, aloe vera ve salicylic acid içeren formüller, cildin nem ihtiyacını karşılayarak fazla yağı dengelemeye yardımcı olur. Gün içinde güneş koruyucu kullanmak da son derece önemlidir. Zinc oxide veya titanium dioxide içeren fiziksel güneş koruyucular, UV ışınlarına karşı koruma sağlarken cildi yağlandırmadan nem dengesini korur.Gece bakımı rutini, cildin onarımını desteklemek için biraz daha farklıdır. İlk adım yine temizliktir; ancak bu sefer daha derinlemesine etki eden bir temizleyici kullanılmalıdır. Glikolik asit veya BHA içeren temizleyiciler, gözenekleri açarak ölü hücrelerin arınmasını sağlar. Gece tonik aşamasında, ciltteki yağı dengelemek için yine alkol içermeyen tonikler tercih edilmelidir.Serum aşamasında, retinol veya niacinamide içeren ürünler, gece boyunca cilt yenilenmesini desteklerken akne oluşumunu azaltmaya yardımcı olur. Yoğun bir nemlendirici yerine, daha hafif bir jel formda nemlendirici kullanmak daha uygundur. Hyaluronik asit ve glycerin içeren hafif nemlendiriciler, cildin su ihtiyacını karşılayarak yağ dengesini korur.Haftada 1-2 kez, ciltteki fazla yağı ve ölü hücreleri temizlemek için bir kil maskesi kullanmak faydalı olacaktır. Bentonit kil veya kaolin içeren maskeler, ciltteki yağı emerken gözenekleri derinlemesine temizler. Bu adımlar ile yağlı cilt bakım rutininiz, cildin sağlıklı ve dengede kalmasına yardımcı olur.", gorsel: UIImage(named: "handCream")!)
        let karmaCilt = Care(isim: "KARMA CİLT", bolge: "Dikkat!: T bölgesi yanaklar",aciklama:"Karma Cilt Bakım Aşamaları Karma cilt bakımı, cildin farklı bölgelerindeki yağ ve nem dengesizliklerini dengelemek için özelleştirilmiş bir yaklaşım gerektirir. Gündüz bakımında ilk adım, cilt temizliğidir. Hyaluronik asit ve seramidler içeren nazik bir temizleyici, cildin nemini kaybetmeden arındırılmasını sağlar. Salicylic acid gibi bileşenler de, yağlı bölgelere etki ederek gözeneklerin temizlenmesine yardımcı olabilir.Temizlikten sonra, alkol içermeyen bir tonik kullanılmalıdır. Niacinamide ve cadı fındığı içeren tonikler, cildin pH dengesini sağlamaya ve yağlı bölgelerdeki parlaklığı azaltmaya yardımcı olur. Ardından serum aşamasına geçilmelidir. C vitamini ve hyaluronik asit içeren serumlar, cildin aydınlanmasını desteklerken nem dengesini korur. Nemlendirme aşamasında, karma ciltler için hafif bir nemlendirici tercih edilmelidir. Aloe vera ve glycerin içeren formüller, ciltte yağlı his bırakmadan nem sağlamaya yardımcı olur. Gündüzleri, geniş spektrumlu bir güneş koruyucu kullanmak son derece önemlidir. Zinc oxide ve titanium dioxide gibi fiziksel güneş koruyucular, UV ışınlarına karşı koruma sağlarken, cildin nem dengesini korumasına da katkıda bulunur.Gece bakımında, ilk adım yine temizliktir. Ancak, karma ciltler için dengeleyici bir temizleyici tercih edilmelidir. Glikolik asit veya BHA içeren temizleyiciler, ciltteki ölü hücreleri arındırarak cildin yenilenmesini destekler. Gece tonik aşamasında, yine alkol içermeyen tonikler kullanılmalıdır. Bu aşamada, çay ağacı yağı ve niacinamide içeren tonikler, akne oluşumunu önlemeye yardımcı olur.Serum aşamasında, cildin ihtiyaçlarına göre retinol veya seramid içeren ürünler kullanılabilir. Retinol, cilt yenilenmesini hızlandırırken, seramidler cilt bariyerini güçlendirir. Nemlendirme için ise, zengin ama hafif bir formüle sahip nemlendirici kullanılmalıdır. Hyaluronik asit, squalane ve vitamin E içeren ürünler, cildin su ihtiyacını karşılar ve yatıştırır.Haftada 1-2 kez, karma ciltler için uygun bir maske kullanmak faydalı olacaktır. Bentonit kil veya kaolin içeren maskeler, yağlı bölgelerdeki fazla yağı emerken, nemlendirici maske ile kuru bölgeleri beslemek, cildin genel dengesini sağlamaya yardımcı olur. Bu adımlarla karma cilt bakım rutininiz, cildin sağlıklı ve dengeli görünmesini destekler.", gorsel: UIImage(named: "mask")!)
        let hassasCilt = Care(isim: "HASSAS CİLT", bolge: "Dikkat!: Yanaklar Göz Çevresi",aciklama:"Hassas Cilt Bakım Aşamaları: Hassas ciltler için bakım, cildin tahriş olmadan nemlenmesini ve yatıştırılmasını sağlamak amacıyla özenle planlanmalıdır. Gündüz bakımına, nazik bir temizleyici ile başlanmalıdır. Aloe vera, camomile (papatya) ve glycerin içeren temizleyiciler, cildi nazikçe arındırırken aynı zamanda yatıştırıcı etkisi ile tahrişi azaltır. Alkol içermeyen bir tonik kullanmak da önemlidir; bu aşamada yeşil çay veya lavanta suyu gibi doğal özler içeren tonikler tercih edilmelidir. Bu tonikler, cildin pH dengesini sağlarken sakinleştirici bir etki gösterir. Temizlik sonrası serum aşamasında, cilt için besleyici bir serum kullanmak gereklidir. Hyaluronik asit, niacinamide ve panthenol içeren serumlar, cildin nem seviyesini artırırken, cilt bariyerini güçlendirmeye yardımcı olur. Nemlendirme aşamasında, hafif ama etkili bir nemlendirici kullanılmalıdır. Shea yağı, squalane ve ceramide içeren formüller, cildin nemini hapsederken cildin doğal bariyerini destekler. Gündüzleri güneş koruyucu kullanmak da son derece önemlidir. Zinc oxide ve titanium dioxide içeren fiziksel güneş koruyucular, cildi UV ışınlarına karşı korurken hassas ciltler için daha az tahriş edici bir seçenektir. Gece bakımında, yine nazik bir temizleyici ile cilt temizlenmelidir. Temizlik sonrasında, cildi yatıştırıcı bir tonik ile dengelemek önemlidir. Bu aşamada, aloe vera ve yeşil çay özleri içeren tonikler tercih edilmelidir. Serum aşamasında, cilt bariyerini güçlendirmek için peptitler ve antioksidanlar içeren ürünler kullanılabilir. Hyaluronik asit ile formüle edilmiş serumlar, cildin derinlemesine nemlenmesini sağlar. Gece nemlendirmesi için, daha yoğun bir formüle sahip nemlendirici kullanılması önerilir. Avokado yağı, kolajen ve hyaluronik asit içeren ürünler, cildin beslenmesini ve onarımını destekler.Haftada 1-2 kez, cildi derinlemesine beslemek için yumuşak bir maske kullanmak da faydalıdır. Yulaf ezmesi ve bal gibi doğal içerikler içeren maskeler, cildi yatıştırır ve nemlendirir. Bu adımlar, hassas cilt bakım rutininizin sağlıklı, dengeli ve huzurlu olmasını sağlar.", gorsel: UIImage(named: "repairCream")!)
        
        let olgunCilt = Care(isim: "OLGUN CİLT", bolge: "Dikkat!:Göz Çevresi, Ağız Çevresi ve Boyun.",aciklama:"Olgun Cilt Bakım Aşamaları:Olgun cilt bakımı, cildin yaşlanma belirtilerini en aza indirmek ve genel görünümünü iyileştirmek için özenle tasarlanmış bir rutini gerektirir. Gündüz bakımına, cilt temizliği ile başlanmalıdır. Krema bazlı veya yağlı formül içeren nazik temizleyiciler, cildin nem dengesini koruyarak arındırma sağlar. Hyaluronik asit, seramid ve vitamin E gibi besleyici içeriklere sahip temizleyiciler, cildin daha pürüzsüz ve dolgun görünmesine katkıda bulunur.Temizlik sonrası tonik aşamasında, cildin pH dengesini sağlamak için alkol içermeyen tonikler tercih edilmelidir. Gül suyu veya yeşil çay özleri içeren tonikler, ciltteki tahrişi azaltırken nemlendirici etki sağlar. Ardından serum aşamasına geçilmelidir. Peptitler, C vitamini ve hyaluronik asit içeren serumlar, cildin elastikiyetini artırarak yaşlanma belirtilerini azaltmaya yardımcı olur.Nemlendirme aşamasında, yoğun bir nemlendirici kullanılması önerilir. Kolajen, avokado yağı ve sheabutter gibi zengin içeriklere sahip ürünler, cildin derinlemesine beslenmesini sağlar ve ince çizgilerin görünümünü azaltır. Gündüzleri geniş spektrumlu bir güneş koruyucu kullanmak, UV hasarını önlemek için kritik öneme sahiptir. Zinc oxide ve titanium dioxide içeren fiziksel güneş koruyucular, cildi korurken ciltte hafif bir beyazlık bırakmadan etkin bir koruma sağlar.Gece bakımında, ilk adım yine nazik bir temizleyici ile cilt temizlenmesidir. Ardından, yatıştırıcı bir tonik kullanılarak cildin pH dengesi sağlanmalıdır. Hyaluronik asit ve gül suyu içeren tonikler, cildi beslerken yatıştırır. Serum aşamasında, gece boyunca onarıcı etkisi olan retinol veya niacinamide içeren ürünler kullanılmalıdır. Bu içerikler, ciltteki hücre yenilenmesini artırarak ince çizgilerin görünümünü azaltır.Nemlendirme aşamasında, daha zengin bir gece kreminin tercih edilmesi gerekmektedir. Kolajen, hyaluronik asit ve avokado yağı içeren gece kremleri, cildin derinlemesine beslenmesine yardımcı olurken, uyku sırasında onarım sürecini destekler. Haftada 1-2 kez, derinlemesine bakım için yoğun bir maske kullanmak da faydalıdır. Yüzdeki yaşlanma belirtilerini azaltan ve cildi besleyen hyaluronik asit ve c vitamini içeren maskeler, cildin daha genç ve canlı görünmesine katkı sağlar. Bu adımlar ile olgun cilt bakım rutininiz, sağlıklı, ışıltılı ve genç bir görünüm kazanmanızı sağlar.", gorsel: UIImage(named: "serums")!)
        
        
        careArray = [normalCilt,kuruCilt,yagliCilt,karmaCilt,hassasCilt,olgunCilt]
        
    }
    

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return careArray.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = UITableViewCell()
        cell.textLabel?.text = careArray[indexPath.row].isim
        return cell
    }

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        selectedCare = careArray[indexPath.row]
        performSegue(withIdentifier: "toDetailsVC", sender: nil)
    }
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "toDetailsVC" {
            let destinationVC = segue.destination as! DetailsViewController
            destinationVC.secilenUrun = selectedCare
            
        }
    }
    
    @IBAction func ciltTipiTiklandi(_ sender: Any) {
      
    }
    
}
